---
  - name: Install Mysql-python
    yum: name=MySQL-python state=latest
  - name: install zabbix repo
    shell: "rpm -Uvh http://repo.zabbix.com/zabbix/4.0/rhel/7/x86_64/zabbix-release-4.0-1.el7.noarch.rpm  --force"
  - name: Install Zabbix Server
    yum: name={{ item }} state=latest
    with_items:
        - zabbix-server-mysql
        - zabbix-web-mysql
  - name: Install httpd
    yum: name=httpd state=latest
  - name: Install Mariadb
    yum: name={{ item }}  state=latest
    with_items:
        - mariadb
        - mariadb-server

  - name: start mariadb
    service: name=mariadb state=started
  - name: change mariadb passwd
    mysql_user: login_host=localhost login_user=root login_password='' user=root password=123456 config_file=/etc/my.cnf
    ignore_errors: True
  - name: create zabbix db
    mysql_db: login_host=localhost login_user=root login_password=123456  name=zabbix state=present config_file=/etc/my.cnf

  - name: import zabbix db
    mysql_db: login_host=localhost login_user=root login_password=123456 config_file=/etc/my.cnf name=zabbix state=import target=/usr/share/doc/zabbix-server-mysql-4.0.1/create.sql.gz
  - name: create zabbix user
    mysql_user: login_host=localhost login_user=root login_password=123456 config_file=/etc/my.cnf user={{ zabbix_db_user }} password={{ zabbix_password }} priv=zabbix.*:ALL state=present
  - name: copy zabbix-server conf
    template: src=zabbix_server.conf.j2 dest=/etc/zabbix/zabbix_server.conf backup=yes
    notify:
    - restart zabbix-server
  - name: copy zabbix-http
    template: src=zabbix.conf.j2 dest=/etc/httpd/conf.d/zabbix.conf backup=yes
    notify:
    - restart http
  - name: start zabbix-server
    service: name=zabbix-server state=started
